name: Mahad's CNC
start:
  must_home: true
  deactivate_parking: false
  check_limits: true
axes:
  x:
    steps_per_mm: 41.667
    max_rate_mm_per_min: 100000
    acceleration_mm_per_sec2: 150
    max_travel_mm: 955
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      feed_mm_per_min: 500.000
      seek_mm_per_min: 2000.000
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.35:low
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.2
        direction_pin: i2so.1
        disable_pin: NO_PIN
  y:
    steps_per_mm: 41.667
    max_rate_mm_per_min: 100000
    acceleration_mm_per_sec2: 150
    max_travel_mm: 863
    soft_limits: true
    homing:
      cycle: 3
      positive_direction: false
      feed_mm_per_min: 500.000
      seek_mm_per_min: 2000.000
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.34:low
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2
      standard_stepper:
        step_pin: i2so.7
        direction_pin: i2so.6
        disable_pin: NO_PIN
  z:
    steps_per_mm: 20.1
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 260
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 2000.000
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.36:low
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.10
        direction_pin: i2so.9
        disable_pin: NO_PIN
  a:
    steps_per_mm: 80
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 1000
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.15
        direction_pin: i2so.14
        disable_pin: NO_PIN
stepping:
  engine: I2S_STREAM
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 0
oled:
  i2c_num: 0
  i2c_address: 60
  width: 128
  height: 64
  radio_delay_ms: 3000
i2c0:
  sda_pin: gpio.14
  scl_pin: gpio.13
control:
  reset_pin: gpio.33:pu:low
  safety_door_pin: NO_PIN
  feed_hold_pin: gpio.16:pu:low
  cycle_start_pin: gpio.4:pu:low
  macro0_pin: NO_PIN
  macro1_pin: gpio.32:pu:low
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  fault_pin: NO_PIN
  estop_pin: NO_PIN
board: None
probe:
  pin: NO_PIN
  toolsetter_pin: NO_PIN
  check_mode_start: false
  hard_stop: false
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17
